version: "3.9"
services:
  db:
    image: "postgres:13"
    container_name: postgres
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - spring-app-net


  spring-boot:
    image: spring-boot-postgres-flyway
    container_name: spring-boot
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - spring-app-net


volumes:
  db-data:

networks:
  spring-app-net:
    name: spring-app-net
